variable "aws_region"      { default = "us-east-1" }
variable "cluster_name"    { default = "mern-cluster" }
variable "vpc_cidr"        { default = "10.0.0.0/16" }
variable "public_subnets"  { default = ["10.0.1.0/24", "10.0.2.0/24"] }
variable "private_subnets" { default = ["10.0.101.0/24", "10.0.102.0/24"] }
variable "key_name"        { type = string }
variable "my_ip"           { type = string }
variable "node_instance_type" { default = "c7i-flex.large" }
variable "desired_capacity"   { default = 2 }
variable "max_size"           { default = 3 }
variable "min_size"           { default = 1 }
