all:
  children:
    jenkins:
      hosts:
        jenkins-server:
          ansible_host: 10.0.101.227    # ← terraform output: jenkins_private_ip
          ansible_user: ubuntu
          ansible_ssh_common_args: >-
            -o ProxyJump=ubuntu@3.239.187.60
            -o StrictHostKeyChecking=yes
            -i ~/.ssh/padmasree.pem
