all:
  children:
    jenkins:
      hosts:
        jenkins-server:
          ansible_host: 10.0.101.227
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /root/.ssh/padmasree.pem
          ansible_ssh_common_args: >-
            -o "ProxyCommand=ssh -i /root/.ssh/padmasree.pem
            -W %h:%p ubuntu@3.239.187.60"
            -o StrictHostKeyChecking=yes
