[jenkins]
jenkins-server ansible_host=52.205.169.19 ansible_user=ubuntu ansible_ssh_private_key_file=/root/padmasree.pem ansible_ssh_common_args='-o StrictHostKeyChecking=yes -o ConnectTimeout=30' ansible_python_interpreter=/usr/bin/python3
